# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'field.ui'
#
# Created: Sat Jun 19 16:36:58 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(608, 553)
        self.vboxlayout = QtGui.QVBoxLayout(Form)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.zoomIn = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomIn.sizePolicy().hasHeightForWidth())
        self.zoomIn.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/viewmag+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomIn.setIcon(icon)
        self.zoomIn.setIconSize(QtCore.QSize(20, 20))
        self.zoomIn.setAutoRepeat(True)
        self.zoomIn.setObjectName("zoomIn")
        self.vboxlayout1.addWidget(self.zoomIn)
        self.zoomOut = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomOut.sizePolicy().hasHeightForWidth())
        self.zoomOut.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/viewmag-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOut.setIcon(icon1)
        self.zoomOut.setIconSize(QtCore.QSize(20, 20))
        self.zoomOut.setAutoRepeat(True)
        self.zoomOut.setObjectName("zoomOut")
        self.vboxlayout1.addWidget(self.zoomOut)
        self.play = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play.sizePolicy().hasHeightForWidth())
        self.play.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/player_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon2)
        self.play.setIconSize(QtCore.QSize(20, 20))
        self.play.setAutoRepeat(True)
        self.play.setObjectName("play")
        self.vboxlayout1.addWidget(self.play)
        self.stop = QtGui.QToolButton(self.layoutWidget)
        self.stop.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/player_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon3)
        self.stop.setIconSize(QtCore.QSize(20, 20))
        self.stop.setAutoRepeat(True)
        self.stop.setObjectName("stop")
        self.vboxlayout1.addWidget(self.stop)
        self.pause = QtGui.QToolButton(self.layoutWidget)
        self.pause.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause.sizePolicy().hasHeightForWidth())
        self.pause.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/player_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon4)
        self.pause.setIconSize(QtCore.QSize(20, 20))
        self.pause.setCheckable(True)
        self.pause.setAutoRepeat(True)
        self.pause.setObjectName("pause")
        self.vboxlayout1.addWidget(self.pause)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.field = QtGui.QGraphicsView(self.layoutWidget)
        self.field.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.field.setObjectName("field")
        self.hboxlayout.addWidget(self.field)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.vboxlayout2.addWidget(self.label)
        self.input = QtGui.QTextEdit(self.layoutWidget1)
        self.input.setObjectName("input")
        self.vboxlayout2.addWidget(self.input)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.vboxlayout2.addWidget(self.label_2)
        self.output = QtGui.QTextBrowser(self.layoutWidget1)
        self.output.setObjectName("output")
        self.vboxlayout2.addWidget(self.output)
        self.hboxlayout1.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setMargin(0)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.vboxlayout4 = QtGui.QVBoxLayout()
        self.vboxlayout4.setSpacing(6)
        self.vboxlayout4.setMargin(0)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.hwall = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hwall.sizePolicy().hasHeightForWidth())
        self.hwall.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/hwall.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hwall.setIcon(icon5)
        self.hwall.setIconSize(QtCore.QSize(20, 20))
        self.hwall.setCheckable(True)
        self.hwall.setObjectName("hwall")
        self.hboxlayout2.addWidget(self.hwall)
        self.vwall = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vwall.sizePolicy().hasHeightForWidth())
        self.vwall.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/vwall.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vwall.setIcon(icon6)
        self.vwall.setIconSize(QtCore.QSize(20, 20))
        self.vwall.setCheckable(True)
        self.vwall.setObjectName("vwall")
        self.hboxlayout2.addWidget(self.vwall)
        self.swall = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swall.sizePolicy().hasHeightForWidth())
        self.swall.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/swall.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.swall.setIcon(icon7)
        self.swall.setIconSize(QtCore.QSize(20, 20))
        self.swall.setCheckable(True)
        self.swall.setObjectName("swall")
        self.hboxlayout2.addWidget(self.swall)
        self.bswall = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bswall.sizePolicy().hasHeightForWidth())
        self.bswall.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/bswall.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bswall.setIcon(icon8)
        self.bswall.setIconSize(QtCore.QSize(20, 20))
        self.bswall.setCheckable(True)
        self.bswall.setObjectName("bswall")
        self.hboxlayout2.addWidget(self.bswall)
        self.vboxlayout4.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.toolButton_5 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/lsluice.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon9)
        self.toolButton_5.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_5.setCheckable(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.hboxlayout3.addWidget(self.toolButton_5)
        self.toolButton_26 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_26.sizePolicy().hasHeightForWidth())
        self.toolButton_26.setSizePolicy(sizePolicy)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/rsluice.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_26.setIcon(icon10)
        self.toolButton_26.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_26.setCheckable(True)
        self.toolButton_26.setObjectName("toolButton_26")
        self.hboxlayout3.addWidget(self.toolButton_26)
        self.toolButton_27 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_27.sizePolicy().hasHeightForWidth())
        self.toolButton_27.setSizePolicy(sizePolicy)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/usluice.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_27.setIcon(icon11)
        self.toolButton_27.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_27.setCheckable(True)
        self.toolButton_27.setObjectName("toolButton_27")
        self.hboxlayout3.addWidget(self.toolButton_27)
        self.toolButton_28 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_28.sizePolicy().hasHeightForWidth())
        self.toolButton_28.setSizePolicy(sizePolicy)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/dsluice.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_28.setIcon(icon12)
        self.toolButton_28.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_28.setCheckable(True)
        self.toolButton_28.setObjectName("toolButton_28")
        self.hboxlayout3.addWidget(self.toolButton_28)
        self.vboxlayout4.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.toolButton_29 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_29.sizePolicy().hasHeightForWidth())
        self.toolButton_29.setSizePolicy(sizePolicy)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/processor.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_29.setIcon(icon13)
        self.toolButton_29.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_29.setCheckable(True)
        self.toolButton_29.setObjectName("toolButton_29")
        self.hboxlayout4.addWidget(self.toolButton_29)
        self.toolButton_30 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_30.sizePolicy().hasHeightForWidth())
        self.toolButton_30.setSizePolicy(sizePolicy)
        self.toolButton_30.setCheckable(True)
        self.toolButton_30.setObjectName("toolButton_30")
        self.hboxlayout4.addWidget(self.toolButton_30)
        self.toolButton_31 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_31.sizePolicy().hasHeightForWidth())
        self.toolButton_31.setSizePolicy(sizePolicy)
        self.toolButton_31.setCheckable(True)
        self.toolButton_31.setObjectName("toolButton_31")
        self.hboxlayout4.addWidget(self.toolButton_31)
        self.toolButton_32 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_32.sizePolicy().hasHeightForWidth())
        self.toolButton_32.setSizePolicy(sizePolicy)
        self.toolButton_32.setCheckable(True)
        self.toolButton_32.setObjectName("toolButton_32")
        self.hboxlayout4.addWidget(self.toolButton_32)
        self.vboxlayout4.addLayout(self.hboxlayout4)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setSpacing(6)
        self.hboxlayout5.setMargin(0)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.toolButton_33 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_33.sizePolicy().hasHeightForWidth())
        self.toolButton_33.setSizePolicy(sizePolicy)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/always.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_33.setIcon(icon14)
        self.toolButton_33.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_33.setCheckable(True)
        self.toolButton_33.setObjectName("toolButton_33")
        self.hboxlayout5.addWidget(self.toolButton_33)
        self.toolButton_34 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_34.sizePolicy().hasHeightForWidth())
        self.toolButton_34.setSizePolicy(sizePolicy)
        self.toolButton_34.setCheckable(True)
        self.toolButton_34.setObjectName("toolButton_34")
        self.hboxlayout5.addWidget(self.toolButton_34)
        self.toolButton_35 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_35.sizePolicy().hasHeightForWidth())
        self.toolButton_35.setSizePolicy(sizePolicy)
        self.toolButton_35.setCheckable(True)
        self.toolButton_35.setObjectName("toolButton_35")
        self.hboxlayout5.addWidget(self.toolButton_35)
        self.toolButton_36 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_36.sizePolicy().hasHeightForWidth())
        self.toolButton_36.setSizePolicy(sizePolicy)
        self.toolButton_36.setCheckable(True)
        self.toolButton_36.setObjectName("toolButton_36")
        self.hboxlayout5.addWidget(self.toolButton_36)
        self.vboxlayout4.addLayout(self.hboxlayout5)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setSpacing(6)
        self.hboxlayout6.setMargin(0)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.toolButton_37 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_37.sizePolicy().hasHeightForWidth())
        self.toolButton_37.setSizePolicy(sizePolicy)
        self.toolButton_37.setCheckable(True)
        self.toolButton_37.setObjectName("toolButton_37")
        self.hboxlayout6.addWidget(self.toolButton_37)
        self.toolButton_38 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_38.sizePolicy().hasHeightForWidth())
        self.toolButton_38.setSizePolicy(sizePolicy)
        self.toolButton_38.setCheckable(True)
        self.toolButton_38.setObjectName("toolButton_38")
        self.hboxlayout6.addWidget(self.toolButton_38)
        self.toolButton_39 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_39.sizePolicy().hasHeightForWidth())
        self.toolButton_39.setSizePolicy(sizePolicy)
        self.toolButton_39.setCheckable(True)
        self.toolButton_39.setObjectName("toolButton_39")
        self.hboxlayout6.addWidget(self.toolButton_39)
        self.toolButton_40 = QtGui.QToolButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_40.sizePolicy().hasHeightForWidth())
        self.toolButton_40.setSizePolicy(sizePolicy)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/terminate.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_40.setIcon(icon15)
        self.toolButton_40.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_40.setCheckable(True)
        self.toolButton_40.setObjectName("toolButton_40")
        self.hboxlayout6.addWidget(self.toolButton_40)
        self.vboxlayout4.addLayout(self.hboxlayout6)
        self.vboxlayout3.addLayout(self.vboxlayout4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem1)
        self.hboxlayout1.addLayout(self.vboxlayout3)
        self.vboxlayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomIn.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOut.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.play.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pause.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.hwall.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.vwall.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.swall.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.bswall.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_26.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_27.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_28.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_29.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_30.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_31.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_32.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_33.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_34.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_35.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_36.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_37.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_38.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_39.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_40.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
